CREATE TABLE CLIENTES (
    ID_CLIENTE INT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    DIRECCION VARCHAR(255),
    TELEFONO VARCHAR(20)
);

CREATE SEQUENCE SEQ_ID_CLIENTE START WITH 1 INCREMENT BY 1;

CREATE TABLE FACTURAS (
    ID_FACTURA INT PRIMARY KEY,
    FECHA DATE NOT NULL,
    ID_CLIENTE INT,
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE)
);

CREATE SEQUENCE SEQ_ID_FACTURA START WITH 1 INCREMENT BY 1;

CREATE TABLE PROVEEDORES (
    ID_PROVEEDOR INT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    DIRECCION VARCHAR(255),
    TELEFONO VARCHAR(20)
);

CREATE TABLE CATEGORIAS (
    ID_CATEGORIA INT PRIMARY KEY,
    DESCRIPCION VARCHAR(100)
);

CREATE TABLE PRODUCTOS (
    ID_PRODUCTO INT PRIMARY KEY,
    DESCRIPCION VARCHAR(255) NOT NULL,
    PRECIO DECIMAL(10,2) NOT NULL,
    ID_CATEGORIA INT,
    ID_PROVEEDOR INT,
    FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIAS(ID_CATEGORIA),
    FOREIGN KEY (ID_PROVEEDOR) REFERENCES PROVEEDORES(ID_PROVEEDOR)
);

CREATE TABLE VENTAS (
    ID_VENTA INT PRIMARY KEY,
    ID_FACTURA INT,
    ID_PRODUCTO INT,
    CANTIDAD INT NOT NULL,
    FOREIGN KEY (ID_FACTURA) REFERENCES FACTURAS(ID_FACTURA),
    FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(ID_PRODUCTO)
);

CREATE SEQUENCE SEQ_ID_VENTA START WITH 1 INCREMENT BY 1;



